# Define the stages of the CI/CD pipeline
stages:
  - pull
  - build
  - push
  - deploy

# Define variables that can be reused
variables:
  DOCKER_IMAGE_NAME: "fe-dumbmerch:latest"

# Job for pulling the repository
pull_repository:
  stage: pull
  script:
    - git clone https://gitlab.com/mabdulzafarassidiq/fe-dumbmerch.git

# Job for building the Docker image
build_image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME ./fe-dumbmerch

# Job for pushing the Docker image to a container registry
push_image:
  stage: push
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push $DOCKER_IMAGE_NAME

# Job for running the image in a container
deploy:
  stage: deploy
  script:
    - ssh appser@103.175.216.224 "docker pull $DOCKER_IMAGE_NAME"
    - ssh appser@103.175.216.224 "docker run -d --name your-app-name -p 80:80 $DOCKER_IMAGE_NAME"

# Define when to run jobs
only:
  - production  # You can specify a specific branch to trigger the CI/CD pipeline
