name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t your-docker-image-name .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag your-docker-image-name $DOCKER_USERNAME/your-docker-image-name:latest
        docker push $DOCKER_USERNAME/your-docker-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into app server and run Docker container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa user@your-app-server "docker pull $DOCKER_USERNAME/your-docker-image-name:latest && docker run -d --name your-app-container $DOCKER_USERNAME/your-docker-image-name:latest"
