name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Docker Configuration
      run: |
        echo "{ 
          \"auths\": { 
            \"https://index.docker.io/v1/\": { 
              \"auth\": \"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\" 
            } 
          } 
        }" > $HOME/.docker/config.json
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t fe-dumbmerch .
        docker push fe-dumbmerch
