name: Pipa CI/CD

on:
  push:
    branches:
      - production

pekerjaan:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Periksa kode
      uses: actions/checkout@v2

    - name: Buat Konfigurasi Docker
      run: |
        echo "{ 
          \"auths\": { 
            \"https://index.docker.io/v1/\": { 
              \"auth\": \"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\" 
            } 
          } 
        }" > $HOME/.docker/config.json
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Bangun dan Unggah Gambar Docker
      run: |
        docker build -t fe-dumbmerch .
        docker push fe-dumbmerch
