name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Repository Pull and SSH Commands
      run: |
        # SSH login
        ssh -o StrictHostKeyChecking=no appser@103.175.216.224 -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") "echo 'Logged in via SSH'"

        # Git pull
        ssh -o StrictHostKeyChecking=no appser@103.175.216.224 -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") "cd /home/appser/fe-dumbmerch && git pull"

        # Build and Push Docker Image
        docker build -t zafarassidiq/fe-dumbmerch .
        docker push zafarassidiq/fe-dumbmerch

        # SSH Deploy
        ssh -o StrictHostKeyChecking=no appser@103.175.216.224 -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") "cd /home/appser/fe-dumbmerch && docker-compose up -d"
