name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: SSH and Git Pull
      run: |
        # SSH login and Git pull
        ssh -o StrictHostKeyChecking=no appser@103.175.216.224 -i - <<<$SSH_PRIVATE_KEY "cd /home/appser/fe-dumbmerch && git pull"

    - name: Build and Push Docker Image
      run: |
        docker build -t ***/fe-dumbmerch .
        docker push ***/fe-dumbmerch

    - name: SSH Deploy
      run: |
        # SSH login and Docker Compose
        ssh -o StrictHostKeyChecking=no appser@103.175.216.224 -i - <<<$SSH_PRIVATE_KEY "cd /home/appser/fe-dumbmerch && docker-compose up -d"
