name: CI/CD Pipeline

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: SSH Login
      uses: appleboy/ssh-action@master
      with:
        host: 103.175.216.224
        username: appser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: 'echo "Logged in to SSH"'

    - name: Build and Push Docker Image
      run: |
        docker build -t zafarassidiq/fe-dumbmerch .
        docker push zafarassidiq/fe-dumbmerch
        
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 103.175.216.224
        username: appser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/appser/fe-dumbmerch
          docker compose up -d

